/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'id' : string,
  'link' : string,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : string,
  'status' : InquiryStatus,
  'name' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type InquiryStatus = { 'new' : null } |
  { 'resolved' : null } |
  { 'inProgress' : null } |
  { 'archived' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface ProductInput {
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBanner' : ActorMethod<[ExternalBlob, string], string>,
  'addInquiry' : ActorMethod<[string, string, string], string>,
  'addProduct' : ActorMethod<[ProductInput], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBanner' : ActorMethod<[string], undefined>,
  'deleteInquiry' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllBanners' : ActorMethod<[], Array<Banner>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBanner' : ActorMethod<[string], Banner>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<string>>,
  'getInquiry' : ActorMethod<[string], Inquiry>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBanner' : ActorMethod<[string, ExternalBlob, string], undefined>,
  'updateInquiryStatus' : ActorMethod<[string, InquiryStatus], undefined>,
  'updateProduct' : ActorMethod<[string, ProductInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];